### ISSUE TITLE
Life history stage linker not updating when next life history stage is deleted

### ISSUE THREAD

**Issue by cstawitz** [wStockhausen/DisMELS#8]
When I delete one of the next life history stages on the LHS Linker, it shows up again as soon as you switch tabs, even if saved immediately after the deletion.

**Comment by wStockhausen** [comment]
Yep, I'm getting the same behavior. A temporary fix (after saving a copy of
the original) would be to delete the entire stage, then re-create it
without the "next" stages you wanted to remove. I'll work on getting it to
work correctly, though.

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.




On Wed, Jan 31, 2018 at 4:05 PM, Christine Stawitz <notifications@github.com

**Comment by cstawitz** [comment]
I've just been fixing it directly in the XML, so it's not blocking me. Thanks!
